# Generated by Django 2.2 on 2020-08-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200731_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='events',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='events',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
