# Generated by Django 2.2 on 2020-08-03 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200731_2356'),
        ('backend', '0006_auto_20200801_0014'),
    ]

    operations = [
    ]
