# Generated by Django 2.2 on 2020-08-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_merge_20200803_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='author',
        ),
    ]
