# Generated by Django 2.2 on 2020-08-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_events_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='events',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
