# Generated by Django 2.2 on 2020-08-05 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200805_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 18, 54, 50, 158438, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 18, 54, 50, 158438, tzinfo=utc), null=True),
        ),
    ]
